### PR TITLE
Deal better with wildcards

### PR DESCRIPTION
**Pull request by gneuvill**

### CODE REVIEW

**Comment by jbgi** [comment]
The fix for GADT TC derivation is welcomed, thanks!

#78 does not appear to be fixed by this PR (tried with your example and a simpler one, with the List). But I don't think it can be fixed in Java for the general case.

**Comment by jbgi** [comment]
rebased in #84

**Comment by gneuvill** [comment]
> #78 does not appear to be fixed by this PR

Probably because it must be used in combination with : https://github.com/derive4j/derive4j-fj/pull/5 ?

**Comment by jbgi** [comment]
@gneuvill I see, I will have a look to that PR now. I merged the related commit in #84 anyway.

**Comment by jbgi** [comment]
merged via #84

**Pull request closed without merging**
