### PR TITLE
Add guava flavour (needs test!)

### PR DESCRIPTION
**Pull request by h908714124**
I would have loved to add a test but wasn't sure where to put it

### CODE REVIEW

**Comment by jbgi** [comment]
Looks good to me! thanks!
For now the tests is mainly the example module: you can add a new data type that use the Guava flavor in there.

**Comment by jbgi** [comment]
Also it looks like your commit is associated with another github account of yours (@anon789) are you ok with that?

**Comment by h908714124** [comment]
No idea what that other account is, I don't care.

**Comment by h908714124** [comment]
Hang on I'll add a test

**Comment by h908714124** [comment]
License problem? I'm stumped!

**Comment by jbgi** [comment]
@h908714124 ah yeah forgot about that: it just need a bsd header. you can add it via "./gradlew licenseFormatTest".
I should probably remove this check from the default build...

**Comment by h908714124** [comment]
didn't help

**Comment by jbgi** [comment]
ok... sorry forgot about the other file in src/main... that is taken care of by "./gradlew licenseFormatMain".

**Comment by jbgi** [comment]
yeah!! thanks!

**Pull request merged**
